name: Auto Instagram Post

# Run every 10 minutes and allow manual trigger
on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_dispatch:          # allows manual trigger

jobs:
  post-confessions:
    runs-on: ubuntu-latest

    env:
      IG_USERNAME: ${{ secrets.IG_USERNAME }}
      IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
      FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

            # 3. Install dependencies
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip && \
             python3 -m pip install -r auto-Instagram-posting-bot/requirements.txt


      # 4. Save Firebase credentials from secret
      - name: Save Firebase JSON
        run: echo "${FIREBASE_JSON}" > auto-Instagram-posting-bot/firebase.json

      # 5. Run the bot
      - name: Run Instagram Bot
        run: python3 auto-Instagram-posting-bot/bot.py

